#!/bin/bash
# Based on the mjpg-streamer by jacksonliam
# For more information
# https://github.com/jacksonliam/mjpg-streamer

description "Install mjpeg-streamer"

messagebox "Install prerequisites"
installer libv4l-dev
installer libjpeg8-dev
installer imagemagick
installer cmake


messagebox "Link library videodev2 to videodev"
ln -sv /usr/include/linux/videodev2.h /usr/include/linux/videodev.h

messagebox "Download mjpeg-streamer from svn to /opt/mjpg-streamer"

gitcloner jacksonliam/mjpg-streamer /opt/mjpg-streamer
cd /opt/mjpg-streamer/mjpg-streamer-experimental
make clean all
make DESTDIR=/usr install
mkdir /opt/user/config/camera

if [ -z /boot/piget/config/camera_pi.json ];then
	cp /boot/piget/config/camera/camera_pi.json /opt/user/config/camera/camera_pi.json
else
	cp /opt/piget/camera/default/camera_pi.json /opt/user/config/camera/camera_pi.json
fi

if [ -z /boot/piget/config/camera_usb.json ];then
	cp /boot/piget/config/camera/camera_usb.json /opt/user/config/camera/camera_usb.json
else
	cp /opt/piget/camera/default/camera_usb.json /opt/user/config/camera/camera_usb.json
fi
