#!/bin/bash
description "Launching mjpg streamer with camera module at 25 fps without password"
echo "Go to "
	listecho $(cat /etc/hostname)":8080"
	listecho $(cat /etc/hostname)".local:8080"
	listecho $(ipAddress)":8080"
messagebox "Press CTRL-C to stop the test"
console
/opt/mjpg-streamer/mjpg-streamer-experimental/mjpg_streamer -o "/opt/mjpg-streamer/mjpg-streamer-experimental/output_http.so -w /usr/www" -i "input_raspicam.so -fps 10 -quality 5"
