#!/bin/bash
description "Test Webcam"
messagebox "Installing Tools"
installer v4l-utils
installer fswebcam
messagebox "Detect Camera"
console
v4l2-ctl --all
webcam_detected=$?
console
if [ $webcam_detected == 1 ]
	then
	colecho "No webcam detected" $ERR
	exit 1
else
	messagebox "Detect Resolutions"
	resolutions=$(v4l2-ctl --list-formats-ext |grep "Size:"|awk '{print $3}')
	echo $resolutions
	colecho "Test all resolutions"
	colecho "Pictures will be saved inside /tmp/webcamTest" $INFO
	mkdir /tmp/webcamTest
	name=$(lsusb |grep -i "cam" |awk '{ $1=""; $2=""; $3=""; $4=""; $5=""; $6=""; print $0 }'|tr -d ' ')

	for resolution in $resolutions
	do
		console
		fswebcam -r "$resolution" -S 5 --save "/tmp/webcamTest"/"$name"-test"$resolution".jpg
		console
	done

	kill -9 $(pgrep -f "python -m SimpleHTTPServer 1234");
	cd /tmp/webcamTest; python -m SimpleHTTPServer 1234 &
	linebreak
	linebreak
	echo "Go to "
	listecho $(cat /etc/hostname)":1234"
	listecho $(cat /etc/hostname)".local:1234"
	listecho $(ipAddress)":1234"
	echo "and check if your webcam works"
	colecho "Press any key to stop sharing pictures" $OK
	read
	linebreak
	linebreak
	kill -9 $(pgrep -f "python -m SimpleHTTPServer 1234");
	rm -rf /tmp/webcamTest
fi

