#!/bin/bash
. /opt/piget/core/install/extendPath
description "Autodetect camera"
cameraState=$(vcgencmd get_camera)
vcgencmd get_camera
if [[ $cameraState == "supported=1 detected=1" ]];then
	cameraTestStreamCameraModule
else
	cameraTestStreamWebcam
fi
