#!/bin/bash
description "Launching mjpg streamer with webcam at 25 fps without password"
echo "Go to "
	listecho $(cat /etc/hostname)":8080"
	listecho $(cat /etc/hostname)".local:8080"
	listecho $(ipAddress)":8080"
messagebox "Press CTRL-C to stop the test"
console
allargs=$("/opt/piget/camera/python/readCameraJson.py" camera_usb.json)

#http://unix.stackexchange.com/questions/163898/how-to-assign-a-string-value-to-a-variable-over-multiple-lines-while-indented
outputArgs=$(echo "${allargs//   /}"|head -n1)
inputArgs=$(echo "${allargs//   /}"|tail -n -1)

if [ $? -eq 0 ];then
	/opt/mjpg-streamer/mjpg-streamer-experimental/mjpg_streamer -o "/opt/mjpg-streamer/mjpg-streamer-experimental/output_http.so -w /usr/www $outputArgs" -i "input_uvc.so $inputArgs"
else
	echo "ERROR IN CONFIG FILE: $args"
fi
