#!/bin/bash
/show/description "Autodetect camera"
cameraState=$(vcgencmd get_camera)
if [[ $cameraState == "supported=1 detected=1" ]];then
	/do/camera/testCameraModule
else
	if [ -e "/dev/video0" ];then
		/do/camera/testWebcam
	else
		/show/listecho "No camera founded (webcam or module) [FAILED]" $ERR
	fi
fi
