#!/bin/bash
/show/description "Autodetect camera"
cameraState=$(vcgencmd get_camera)
if [[ $cameraState == "supported=1 detected=1" ]];then
	/do/camera/testCameraModule
else
	/do/camera/testWebcam
fi
